import { IData } from "../type/type"

export const Datax = [
    {
        "name": "Tokyo Design Institute",
        "course_name": "Graphic Design",
        "short_name": "Design",
        "price": 38000,
        "duration": "2 years",
        "location": "Japan",
        "address": "Tokyo, Japan",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "shortsummery": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus molestie vestibulum magna nec lacinia. Quisque non turpis eu leo semper ullamcorper. Duis ut nulla eu sem vestibulum efficitur. Morbi vitae nulla sit amet mi tristique dictum sed non nisi. Proin nec elit eget velit consequat pretium. Integer rutrum posuere diam, nec sollicitudin justo interdum nec. Maecenas sed felis vel felis aliquet tempus. Cras id neque vel nunc condimentum viverra. Sed ut erat vitae nisi dictum dignissim. Sed quis lacus et justo consequat tincidunt. Sed id arcu diam.",
        "summary": "The Tokyo Design Institute in Japan offers graduate programs in graphic design. Students explore visual communication, typography, and digital media design. The program duration is 2 years. The institute is located in Tokyo, Japan. Tokyo, with its blend of traditional culture and modern innovation, provides students with a dynamic and inspiring environment to develop their skills in graphic design. With a history spanning centuries and a culture that values aesthetics and creativity, Tokyo serves as the perfect backdrop for students to immerse themselves in the world of graphic design.",
        "discipline": "Graphic Design",
        "cost_of_living": "$70,000 per year",
        "fee": 250
    },
    {
        "name": "Los Angeles Film Academy",
        "course_name": "Film Production",
        "short_name": "Film Making",
        "price": 42000,
        "duration": "2 years",
        "location": "USA",
        "address": "Los Angeles, USA",
        "shortsummery": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus molestie vestibulum magna nec lacinia. Quisque non turpis eu leo semper ullamcorper. Duis ut nulla eu sem vestibulum efficitur. Morbi vitae nulla sit amet mi tristique dictum sed non nisi. Proin nec elit eget velit consequat pretium. Integer rutrum posuere diam, nec sollicitudin justo interdum nec. Maecenas sed felis vel felis aliquet tempus. Cras id neque vel nunc condimentum viverra. Sed ut erat vitae nisi dictum dignissim. Sed quis lacus et justo consequat tincidunt. Sed id arcu diam.",

        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Los Angeles Film Academy in the USA offers graduate programs in film production. Students learn about screenwriting, directing, and cinematography through hands-on projects and workshops. The program duration is 2 years. The academy is located in Los Angeles, USA. Los Angeles, with its thriving entertainment industry and diverse cultural landscape, provides students with a vibrant and immersive experience in film production. Known as the entertainment capital of the world, Los Angeles offers students unparalleled opportunities to network and collaborate within the film industry.",
        "discipline": "Film Production",
        "cost_of_living": "$85,000 per year",
        "fee": 280
    },
    {
        "name": "Milan Fashion Institute",
        "course_name": "Fashion Design",
        "short_name": "Fashion Designing",
        "price": 40000,
        "duration": "2 years",
        "location": "Italy",
        "address": "Milan, Italy",
        "shortsummery": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus molestie vestibulum magna nec lacinia. Quisque non turpis eu leo semper ullamcorper. Duis ut nulla eu sem vestibulum efficitur. Morbi vitae nulla sit amet mi tristique dictum sed non nisi. Proin nec elit eget velit consequat pretium. Integer rutrum posuere diam, nec sollicitudin justo interdum nec. Maecenas sed felis vel felis aliquet tempus. Cras id neque vel nunc condimentum viverra. Sed ut erat vitae nisi dictum dignissim. Sed quis lacus et justo consequat tincidunt. Sed id arcu diam.",

        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Milan Fashion Institute in Italy offers undergraduate programs in fashion design. Students explore various aspects of fashion, including design, textiles, and marketing. The program duration is 2 years. The institute is located in Milan, Italy. Milan, known as one of the world's fashion capitals, provides students with a rich cultural and creative environment to develop their skills in fashion design. With its renowned fashion houses and vibrant street style, Milan serves as a hub for innovation and creativity in the fashion industry.",
        "discipline": "Fashion Design",
        "cost_of_living": "$75,000 per year",
        "fee": 220
    },
    {
        "name": "Dublin Culinary School",
        "course_name": "Culinary Arts",
        "short_name": "Culinary",
        "price": 35000,
        "duration": "2 years",
        "location": "Ireland",
        "address": "Dublin, Ireland",
        "shortsummery": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus molestie vestibulum magna nec lacinia. Quisque non turpis eu leo semper ullamcorper. Duis ut nulla eu sem vestibulum efficitur. Morbi vitae nulla sit amet mi tristique dictum sed non nisi. Proin nec elit eget velit consequat pretium. Integer rutrum posuere diam, nec sollicitudin justo interdum nec. Maecenas sed felis vel felis aliquet tempus. Cras id neque vel nunc condimentum viverra. Sed ut erat vitae nisi dictum dignissim. Sed quis lacus et justo consequat tincidunt. Sed id arcu diam.",

        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Dublin Culinary School in Ireland offers undergraduate programs in culinary arts. Students learn classic cooking techniques and culinary traditions from around the world. The program duration is 2 years. The school is located in Dublin, Ireland. Dublin, with its vibrant food scene and diverse culinary influences, provides students with an exciting and enriching environment to develop their skills in culinary arts. From traditional Irish dishes to international cuisines, Dublin offers a culinary journey like no other.",
        "discipline": "Culinary Arts",
        "cost_of_living": "$70,000 per year",
        "fee": 250
    },
    {
        "name": "London School of Economics",
        "course_name": "Economics",
        "short_name": "Economics",
        "price": 45000,
        "duration": "2 years",
        "location": "UK",
        "address": "London, UK",
        "shortsummery": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus molestie vestibulum magna nec lacinia. Quisque non turpis eu leo semper ullamcorper. Duis ut nulla eu sem vestibulum efficitur. Morbi vitae nulla sit amet mi tristique dictum sed non nisi. Proin nec elit eget velit consequat pretium. Integer rutrum posuere diam, nec sollicitudin justo interdum nec. Maecenas sed felis vel felis aliquet tempus. Cras id neque vel nunc condimentum viverra. Sed ut erat vitae nisi dictum dignissim. Sed quis lacus et justo consequat tincidunt. Sed id arcu diam.",

        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Graduate",
        "summary": "The London School of Economics in the UK offers graduate programs in economics. Students delve into economic theory, policy analysis, and quantitative methods. The program duration is 2 years. The school is located in London, UK. London, as a global financial hub and cultural center, provides students with access to leading economists and policymakers, offering a unique perspective on economic issues. With its rich history and diverse population, London is an ideal location for studying economics.",
        "discipline": "Economics",
        "cost_of_living": "$90,000 per year",
        "fee": 300
    },
    {
        "name": "Seoul Technology Institute",
        "course_name": "Computer Science",
        "short_name": "Computer Science",
        "price": 38000,
        "duration": "2 years",
        "location": "South Korea",
        "address": "Seoul, South Korea",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Seoul Technology Institute in South Korea offers graduate programs in computer science. Students study algorithms, data structures, and software engineering principles. The program duration is 2 years. The institute is located in Seoul, South Korea. Seoul, with its technological innovation and dynamic startup culture, provides students with a stimulating environment to study computer science and pursue careers in technology.",
        "discipline": "Computer Science",
        "cost_of_living": "$65,000 per year",
        "fee": 250
    },
    {
        "name": "Toronto Film School",
        "course_name": "Film Studies",
        "short_name": "Film Studies",
        "price": 40000,
        "duration": "2 years",
        "location": "Canada",
        "address": "Toronto, Canada",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Graduate",
        "summary": "The Toronto Film School in Canada offers graduate programs in film studies. Students explore film history, theory, and criticism while also gaining practical filmmaking skills. The program duration is 2 years. The school is located in Toronto, Canada. Toronto, with its diverse and multicultural population, provides students with a rich cultural tapestry and a thriving film industry to explore and engage with during their studies.",
        "discipline": "Film Studies",
        "cost_of_living": "$80,000 per year",
        "fee": 270
    },
    {
        "name": "Munich Automotive Engineering Institute",
        "course_name": "Automotive Engineering",
        "short_name": "Automotive",
        "price": 38000,
        "duration": "2 years",
        "location": "Germany",
        "address": "Munich, Germany",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Munich Automotive Engineering Institute in Germany offers graduate programs in automotive engineering. Students study vehicle design, propulsion systems, and advanced materials. The program duration is 2 years. The institute is located in Munich, Germany. Munich, with its strong automotive industry and technological innovation, provides students with a stimulating environment to study automotive engineering and pursue careers in the automotive sector.",
        "discipline": "Automotive Engineering",
        "cost_of_living": "$70,000 per year",
        "fee": 250
    },
    {
        "name": "Florence Art Academy",
        "course_name": "Fine Arts",
        "short_name": "Fine Arts",
        "price": 32000,
        "duration": "2 years",
        "location": "Italy",
        "address": "Florence, Italy",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Florence Art Academy in Italy offers undergraduate programs in fine arts. Students explore various artistic techniques, including painting, sculpture, and drawing. The program duration is 2 years. The academy is located in Florence, Italy. Florence, renowned for its Renaissance art and architecture, provides students with a rich cultural heritage and artistic inspiration. With its museums, galleries, and historical landmarks, Florence offers a unique environment for students to develop their artistic talents.",
        "discipline": "Fine Arts",
        "cost_of_living": "$60,000 per year",
        "fee": 200
    },
    {
        "name": "Dublin Writing Institute",
        "course_name": "Creative Writing",
        "short_name": "Writing",
        "price": 32000,
        "duration": "2 years",
        "location": "Ireland",
        "address": "Dublin, Ireland",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Dublin Writing Institute in Ireland offers graduate programs in creative writing. Students explore various forms of writing, including fiction, poetry, and screenwriting. The program duration is 2 years. The institute is located in Dublin, Ireland. Dublin, with its rich literary history and vibrant cultural scene, provides students with a stimulating and supportive environment to develop their writing skills. With its literary festivals, writing workshops, and vibrant community of writers, Dublin offers a dynamic setting for aspiring authors.",
        "discipline": "Creative Writing",
        "cost_of_living": "$55,000 per year",
        "fee": 210
    },
    {
        "name": "Manchester Language School",
        "course_name": "English Language",
        "short_name": "English Language",
        "price": 30000,
        "duration": "2 years",
        "location": "UK",
        "address": "Manchester, UK",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Language Certification",
        "summary": "The Manchester Language School in the UK offers language certification programs in English. Students improve their language skills through immersive courses and cultural activities. The program duration is 2 years. The school is located in Manchester, UK. Manchester, with its diverse population and rich cultural heritage, provides students with an ideal environment to learn English. With its vibrant arts scene and friendly locals, Manchester offers a welcoming and supportive setting for language learners.",
        "discipline": "English Language",
        "cost_of_living": "$65,000 per year",
        "fee": 200
    },
    {
        "name": "Seoul Dance Academy",
        "course_name": "Dance Performance",
        "short_name": "Dance",
        "price": 30000,
        "duration": "2 years",
        "location": "South Korea",
        "address": "Seoul, South Korea",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Seoul Dance Academy in South Korea offers undergraduate programs in dance performance. Students receive rigorous training in various dance styles, including ballet, contemporary, and jazz. The program duration is 2 years. The academy is located in Seoul, South Korea. Seoul, with its vibrant arts scene and passionate dance community, provides students with a dynamic and inspiring environment to pursue their passion for dance. With its numerous dance studios, theaters, and performance venues, Seoul offers students ample opportunities to showcase their talents and grow as dancers.",
        "discipline": "Dance Performance",
        "cost_of_living": "$65,000 per year",
        "fee": 200
    },
    {
        "name": "Berlin Business School",
        "course_name": "Business Administration",
        "short_name": "Business",
        "price": 45000,
        "duration": "2 years",
        "location": "Germany",
        "address": "Berlin, Germany",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Graduate",
        "summary": "The Berlin Business School in Germany offers graduate programs in business administration. Students learn about finance, marketing, and strategic management. The program duration is 2 years. The school is located in Berlin, Germany. Berlin, with its vibrant startup scene and multicultural atmosphere, provides students with a dynamic environment to study business administration. With its thriving economy and innovative spirit, Berlin offers students unique opportunities to engage with real-world business challenges.",
        "discipline": "Business Administration",
        "cost_of_living": "$90,000 per year",
        "fee": 300
    },
    {
        "name": "Vancouver Technology Institute",
        "course_name": "Software Engineering",
        "short_name": "Software Engineering",
        "price": 38000,
        "duration": "2 years",
        "location": "Canada",
        "address": "Vancouver, Canada",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Vancouver Technology Institute in Canada offers graduate programs in software engineering. Students study programming languages, algorithms, and software development methodologies. The program duration is 2 years. The institute is located in Vancouver, Canada. Vancouver, with its booming tech industry and stunning natural scenery, provides students with an ideal environment to study software engineering. With its diverse workforce and innovative companies, Vancouver offers students numerous opportunities to collaborate on cutting-edge projects and gain real-world experience.",
        "discipline": "Software Engineering",
        "cost_of_living": "$65,000 per year",
        "fee": 250
    },
    {
        "name": "Rome Culinary Institute",
        "course_name": "Culinary Arts",
        "short_name": "Culinary",
        "price": 35000,
        "duration": "2 years",
        "location": "Italy",
        "address": "Rome, Italy",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Rome Culinary Institute in Italy offers undergraduate programs in culinary arts. Students learn traditional Italian cooking techniques and culinary traditions. The program duration is 2 years. The institute is located in Rome, Italy. Rome, with its rich culinary heritage and emphasis on fresh, seasonal ingredients, provides students with an authentic and immersive culinary education experience. With its bustling markets, family-owned trattorias, and world-renowned cuisine, Rome offers students a taste of la dolce vita.",
        "discipline": "Culinary Arts",
        "cost_of_living": "$70,000 per year",
        "fee": 250
    },
    {
        "name": "Sydney Photography School",
        "course_name": "Photography",
        "short_name": "Photography",
        "price": 32000,
        "duration": "2 years",
        "location": "Australia",
        "address": "Sydney, Australia",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Sydney Photography School in Australia offers undergraduate programs in photography. Students explore various photography techniques, including digital imaging and photojournalism. The program duration is 2 years. The school is located in Sydney, Australia. Sydney, with its stunning landscapes and vibrant cultural scene, provides students with diverse and picturesque settings to develop their skills in photography. From iconic landmarks to hidden gems, Sydney offers endless opportunities for creative exploration and artistic expression.",
        "discipline": "Photography",
        "cost_of_living": "$75,000 per year",
        "fee": 220
    },
    {
        "name": "Boston Film Academy",
        "course_name": "Film Production",
        "short_name": "Film Making",
        "price": 42000,
        "duration": "2 years",
        "location": "USA",
        "address": "Boston, USA",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Boston Film Academy in the USA offers graduate programs in film production. Students gain practical experience in filmmaking, from scriptwriting to post-production. The program duration is 2 years. The academy is located in Boston, USA. Boston, with its rich history and vibrant arts scene, provides students with a supportive and creative environment to pursue their passion for filmmaking. With its numerous film festivals, production companies, and cultural institutions, Boston offers students a wealth of opportunities to showcase their talents and connect with industry professionals.",
        "discipline": "Film Production",
        "cost_of_living": "$85,000 per year",
        "fee": 280
    },
    {
        "name": "Melbourne Fashion Institute",
        "course_name": "Fashion Design",
        "short_name": "Fashion Designing",
        "price": 40000,
        "duration": "2 years",
        "location": "Australia",
        "address": "Melbourne, Australia",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Melbourne Fashion Institute in Australia offers undergraduate programs in fashion design. Students explore fashion trends, garment construction, and fashion marketing. The program duration is 2 years. The institute is located in Melbourne, Australia. Melbourne, known for its vibrant street art and eclectic fashion scene, provides students with a dynamic and multicultural environment to study fashion design. With its fashion festivals, boutique shops, and fashion-forward neighborhoods, Melbourne offers students endless inspiration and opportunities to showcase their creativity.",
        "discipline": "Fashion Design",
        "cost_of_living": "$70,000 per year",
        "fee": 250
    },
    {
        "name": "Paris Culinary Institute",
        "course_name": "Culinary Arts",
        "short_name": "Culinary",
        "price": 35000,
        "duration": "2 years",
        "location": "France",
        "address": "Paris, France",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Paris Culinary Institute in France offers undergraduate programs in culinary arts. Students learn classic French cooking techniques and culinary traditions. The program duration is 2 years. The institute is located in Paris, France. Paris, with its reputation as the culinary capital of the world, provides students with an unparalleled gastronomic experience. From Michelin-starred restaurants to quaint bistros, Paris offers students a taste of French culture and cuisine.",
        "discipline": "Culinary Arts",
        "cost_of_living": "$80,000 per year",
        "fee": 270
    },
    {
        "name": "New York Art Academy",
        "course_name": "Fine Arts",
        "short_name": "Fine Arts",
        "price": 32000,
        "duration": "2 years",
        "location": "USA",
        "address": "New York, USA",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The New York Art Academy in the USA offers undergraduate programs in fine arts. Students explore various artistic mediums, including painting, sculpture, and printmaking. The program duration is 2 years. The academy is located in New York, USA. New York, with its vibrant arts scene and diverse cultural influences, provides students with endless inspiration and opportunities to explore their creativity. From world-class museums to cutting-edge galleries, New York offers students a dynamic and stimulating environment to pursue their passion for the arts.",
        "discipline": "Fine Arts",
        "cost_of_living": "$90,000 per year",
        "fee": 300
    },
    {
        "name": "Berlin Music Academy",
        "course_name": "Music Production",
        "short_name": "Music",
        "price": 32000,
        "duration": "2 years",
        "location": "Germany",
        "address": "Berlin, Germany",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Berlin Music Academy in Germany offers graduate programs in music production. Students learn about music theory, composition, and audio engineering. The program duration is 2 years. The academy is located in Berlin, Germany. Berlin, with its vibrant music scene and experimental spirit, provides students with an inspiring environment to study music production. From underground clubs to world-renowned concert halls, Berlin offers students a diverse range of musical experiences and opportunities to collaborate with fellow musicians.",
        "discipline": "Music Production",
        "cost_of_living": "$70,000 per year",
        "fee": 250
    },
    {
        "name": "Dubai Business School",
        "course_name": "Business Administration",
        "short_name": "Business",
        "price": 45000,
        "duration": "2 years",
        "location": "UAE",
        "address": "Dubai, UAE",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Graduate",
        "summary": "The Dubai Business School in the UAE offers graduate programs in business administration. Students gain practical skills in management, marketing, and finance. The program duration is 2 years. The school is located in Dubai, UAE. Dubai, with its thriving economy and strategic location, provides students with unique insights into global business trends and practices. With its dynamic business environment and multicultural workforce, Dubai offers students a rich and immersive experience in business education.",
        "discipline": "Business Administration",
        "cost_of_living": "$90,000 per year",
        "fee": 300
    },
    {
        "name": "Barcelona Art Institute",
        "course_name": "Visual Arts",
        "short_name": "Visual Arts",
        "price": 32000,
        "duration": "2 years",
        "location": "Spain",
        "address": "Barcelona, Spain",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Barcelona Art Institute in Spain offers undergraduate programs in visual arts. Students explore various artistic mediums, including painting, sculpture, and digital art. The program duration is 2 years. The institute is located in Barcelona, Spain. Barcelona, with its vibrant arts scene and architectural wonders, provides students with endless inspiration and opportunities to develop their artistic talents. From Gaudi's masterpieces to contemporary art galleries, Barcelona offers students a dynamic and culturally rich environment to pursue their passion for the visual arts.",
        "discipline": "Visual Arts",
        "cost_of_living": "$70,000 per year",
        "fee": 250
    },
    {
        "name": "Vienna Music Academy",
        "course_name": "Music Composition",
        "short_name": "Music Composition",
        "price": 32000,
        "duration": "2 years",
        "location": "Austria",
        "address": "Vienna, Austria",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Vienna Music Academy in Austria offers graduate programs in music composition. Students study music theory, orchestration, and music history. The program duration is 2 years. The academy is located in Vienna, Austria. Vienna, with its rich musical heritage and historic concert halls, provides students with a stimulating environment to study music composition. From Mozart to Beethoven, Vienna's musical legacy inspires students to create their own compositions and push the boundaries of contemporary music.",
        "discipline": "Music Composition",
        "cost_of_living": "$70,000 per year",
        "fee": 250
    },
    {
        "name": "Tokyo Technology Institute",
        "course_name": "Information Technology",
        "short_name": "Information Technology",
        "price": 38000,
        "duration": "2 years",
        "location": "Japan",
        "address": "Tokyo, Japan",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Tokyo Technology Institute in Japan offers graduate programs in information technology. Students learn about database management, cybersecurity, and software development. The program duration is 2 years. The institute is located in Tokyo, Japan. Tokyo, with its cutting-edge technology and innovative startups, provides students with a dynamic environment to study information technology. From robotics to artificial intelligence, Tokyo offers students a glimpse into the future of technology and prepares them for careers in the digital age.",
        "discipline": "Information Technology",
        "cost_of_living": "$65,000 per year",
        "fee": 250
    },
    {
        "name": "Singapore Business School",
        "course_name": "Business Analytics",
        "short_name": "Business Analytics",
        "price": 45000,
        "duration": "2 years",
        "location": "Singapore",
        "address": "Singapore",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Graduate",
        "summary": "The Singapore Business School in Singapore offers graduate programs in business analytics. Students learn about data analysis, predictive modeling, and data visualization. The program duration is 2 years. The school is located in Singapore. Singapore, with its strategic location and vibrant business ecosystem, provides students with unique opportunities to study business analytics. With its world-class infrastructure and supportive government policies, Singapore is a leading hub for data-driven innovation and entrepreneurship.",
        "discipline": "Business Analytics",
        "cost_of_living": "$80,000 per year",
        "fee": 300
    },
    {
        "name": "Florence Fashion Institute",
        "course_name": "Fashion Marketing",
        "short_name": "Fashion Marketing",
        "price": 40000,
        "duration": "2 years",
        "location": "Italy",
        "address": "Florence, Italy",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Graduate",
        "summary": "The Florence Fashion Institute in Italy offers graduate programs in fashion marketing. Students learn about branding, retail management, and fashion merchandising. The program duration is 2 years. The institute is located in Florence, Italy. Florence, renowned for its fashion heritage and luxury craftsmanship, provides students with a unique opportunity to study fashion marketing in the heart of Italy's fashion industry. With its fashion events, trade fairs, and historical landmarks, Florence offers students a dynamic and inspiring environment to explore the business side of fashion.",
        "discipline": "Fashion Marketing",
        "cost_of_living": "$70,000 per year",
        "fee": 250
    },
    {
        "name": "London Film Academy",
        "course_name": "Film Directing",
        "short_name": "Film Directing",
        "price": 42000,
        "duration": "2 years",
        "location": "UK",
        "address": "London, UK",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The London Film Academy in the UK offers graduate programs in film directing. Students gain practical experience in directing, from script analysis to casting. The program duration is 2 years. The academy is located in London, UK. London, with its rich cinematic history and vibrant cultural scene, provides students with a stimulating environment to study film directing. From iconic film studios to independent cinemas, London offers students numerous opportunities to engage with the film industry and develop their directorial skills.",
        "discipline": "Film Directing",
        "cost_of_living": "$85,000 per year",
        "fee": 280
    },
    {
        "name": "Tokyo Environmental Studies Institute",
        "course_name": "Environmental Sciences",
        "short_name": "Environmental",
        "price": 34000,
        "duration": "2 years",
        "location": "Japan",
        "address": "Tokyo, Japan",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Postdoctoral",
        "summary": "The Tokyo Environmental Studies Institute in Japan offers postdoctoral programs in environmental sciences. Students conduct innovative research to address pressing environmental issues. The program duration is 2 years. The institute is located in Tokyo, Japan. Tokyo is a vibrant city known for its blend of traditional culture and modern innovation. Students benefit from a rich academic environment and access to cutting-edge facilities.",
        "discipline": "Environmental Sciences",
        "cost_of_living": "$70,000 per year",
        "fee": 170
    },
    {
        "name": "Sydney Language Academy",
        "course_name": "Language Studies",
        "short_name": "Language",
        "price": 15000,
        "duration": "18 months",
        "location": "Australia",
        "address": "Sydney, Australia",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Language Certification",
        "summary": "The Sydney Language Academy in Australia offers language certification programs for various languages. Students immerse themselves in the language and culture, gaining proficiency and certification. The program duration is 18 months. The academy is located in Sydney, Australia. Sydney is a multicultural hub with stunning beaches and a thriving arts scene, offering students a diverse and vibrant learning environment.",
        "discipline": "Language Studies",
        "cost_of_living": "$50,000 per year",
        "fee": 200
    },
    {
        "name": "Berlin Music Institute",
        "course_name": "Music Performance",
        "short_name": "Music",
        "price": 40000,
        "duration": "3 years",
        "location": "Germany",
        "address": "Berlin, Germany",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Graduate",
        "summary": "The Berlin Music Institute in Germany offers graduate programs in music performance. Students receive rigorous training and mentorship from renowned musicians. The program duration is 3 years. The institute is located in Berlin, Germany. Berlin is a cultural hotspot known for its thriving music scene and historical landmarks, providing students with a rich and inspiring setting for their studies.",
        "discipline": "Music Performance",
        "cost_of_living": "$60,000 per year",
        "fee": 250
    },
    {
        "name": "Vienna Space Exploration Center",
        "course_name": "Space Exploration",
        "short_name": "Space",
        "price": 50000,
        "duration": "4 years",
        "location": "Austria",
        "address": "Vienna, Austria",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Vienna Space Exploration Center in Austria offers graduate programs in space exploration. Students engage in cutting-edge research and hands-on projects. The program duration is 4 years. The center is located in Vienna, Austria. Vienna is renowned for its history, culture, and scientific achievements, providing students with a stimulating environment to explore the mysteries of space.",
        "discipline": "Space Exploration",
        "cost_of_living": "$65,000 per year",
        "fee": 300
    },
    {
        "name": "Paris Environmental Academy",
        "course_name": "Environmental Sciences",
        "short_name": "Environmental",
        "price": 20000,
        "duration": "1 year",
        "location": "France",
        "address": "Paris, France",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Diploma",
        "summary": "The Paris Environmental Academy in France offers diploma programs in environmental sciences. Students receive comprehensive training in environmental conservation and sustainability. The program duration is 1 year. The academy is located in Paris, France. Paris, the city of lights, is renowned for its beauty and cultural heritage, providing students with an inspiring backdrop for their studies in environmental sciences.",
        "discipline": "Environmental Sciences",
        "cost_of_living": "$75,000 per year",
        "fee": 150
    },
    {
        "name": "New York Language Academy",
        "course_name": "Language Studies",
        "short_name": "Language",
        "price": 8000,
        "duration": "1 year",
        "location": "USA",
        "address": "New York, USA",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring", "Fall"],
        "program_level": "Language Certification",
        "summary": "The New York Language Academy in the USA offers language certification programs for international students. Students immerse themselves in the English language and American culture, gaining fluency and cultural competence. The program duration is 1 year. The academy is located in New York, USA. New York City is a global melting pot with diverse communities and endless opportunities, making it an ideal destination for language learning and cultural exchange.",
        "discipline": "Language Studies",
        "cost_of_living": "$80,000 per year",
        "fee": 100
    },
    {
        "name": "Toronto Film Institute",
        "course_name": "Film Production",
        "short_name": "Film",
        "price": 30000,
        "duration": "2 years",
        "location": "Canada",
        "address": "Toronto, Canada",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Toronto Film Institute in Canada offers undergraduate programs in film production. Students learn the art and craft of filmmaking through hands-on experience and theoretical study. The program duration is 2 years. The institute is located in Toronto, Canada. Toronto is a dynamic city with a vibrant film industry and multicultural atmosphere, providing students with a stimulating environment to pursue their passion for filmmaking.",
        "discipline": "Film Production",
        "cost_of_living": "$55,000 per year",
        "fee": 220
    },
    {
        "name": "London Fashion School",
        "course_name": "Fashion Design",
        "short_name": "Fashion",
        "price": 45000,
        "duration": "3 years",
        "location": "UK",
        "address": "London, UK",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The London Fashion School in the UK offers graduate programs in fashion design. Students explore creativity and innovation in fashion through practical projects and industry collaboration. The program duration is 3 years. The school is located in London, UK. London is a global fashion capital with a rich heritage in design and a thriving creative scene, providing students with endless inspiration and opportunities to pursue their passion for fashion.",
        "discipline": "Fashion Design",
        "cost_of_living": "$90,000 per year",
        "fee": 250
    },
    {
        "name": "Rome Culinary Institute",
        "course_name": "Culinary Arts",
        "short_name": "Culinary",
        "price": 25000,
        "duration": "2 years",
        "location": "Italy",
        "address": "Rome, Italy",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Rome Culinary Institute in Italy offers undergraduate programs in culinary arts. Students learn the art of cooking from expert chefs and gain hands-on experience in professional kitchens. The program duration is 2 years. The institute is located in Rome, Italy. Rome, the eternal city, is renowned for its culinary traditions and rich gastronomic culture, providing students with a flavorful and immersive learning experience.",
        "discipline": "Culinary Arts",
        "cost_of_living": "$70,000 per year",
        "fee": 180
    },
    {
        "name": "Barcelona Art Academy",
        "course_name": "Fine Arts",
        "short_name": "Fine Arts",
        "price": 30000,
        "duration": "3 years",
        "location": "Spain",
        "address": "Barcelona, Spain",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Barcelona Art Academy in Spain offers graduate programs in fine arts. Students explore various artistic mediums and techniques under the guidance of experienced faculty. The program duration is 3 years. The academy is located in Barcelona, Spain. Barcelona is a vibrant city known for its rich artistic heritage and contemporary art scene, providing students with an inspiring environment to unleash their creativity and pursue their passion for fine arts.",
        "discipline": "Fine Arts",
        "cost_of_living": "$65,000 per year",
        "fee": 250
    },
    {
        "name": "Berlin Film Institute",
        "course_name": "Film Studies",
        "short_name": "Film",
        "price": 35000,
        "duration": "2 years",
        "location": "Germany",
        "address": "Berlin, Germany",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Berlin Film Institute in Germany offers undergraduate programs in film studies. Students explore the history, theory, and practice of filmmaking through hands-on projects and academic study. The program duration is 2 years. The institute is located in Berlin, Germany. Berlin is a cultural hub with a thriving film industry and vibrant arts scene, providing students with a dynamic and inspiring environment to study film.",
        "discipline": "Film Studies",
        "cost_of_living": "$60,000 per year",
        "fee": 220
    },
    {
        "name": "Sydney Culinary Institute",
        "course_name": "Culinary Arts",
        "short_name": "Culinary",
        "price": 28000,
        "duration": "2 years",
        "location": "Australia",
        "address": "Sydney, Australia",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Undergraduate",
        "summary": "The Sydney Culinary Institute in Australia offers undergraduate programs in culinary arts. Students learn essential culinary skills and techniques from industry professionals. The program duration is 2 years. The institute is located in Sydney, Australia. Sydney is known for its diverse culinary scene and fresh local produce, providing students with a rich and flavorful learning experience in the culinary arts.",
        "discipline": "Culinary Arts",
        "cost_of_living": "$50,000 per year",
        "fee": 200
    },
    {
        "name": "Vienna Music Academy",
        "course_name": "Music Composition",
        "short_name": "Music",
        "price": 38000,
        "duration": "3 years",
        "location": "Austria",
        "address": "Vienna, Austria",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The Vienna Music Academy in Austria offers graduate programs in music composition. Students receive comprehensive training in composition techniques and music theory. The program duration is 3 years. The academy is located in Vienna, Austria. Vienna is a cultural capital with a rich musical heritage and vibrant arts scene, providing students with an inspiring environment to develop their skills and creativity in music composition.",
        "discipline": "Music Composition",
        "cost_of_living": "$65,000 per year",
        "fee": 250
    },
    {
        "name": "Paris Fashion School",
        "course_name": "Fashion Marketing",
        "short_name": "Fashion",
        "price": 32000,
        "duration": "2 years",
        "location": "France",
        "address": "Paris, France",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Graduate",
        "summary": "The Paris Fashion School in France offers graduate programs in fashion marketing. Students learn about branding, consumer behavior, and market trends in the fashion industry. The program duration is 2 years. The school is located in Paris, France. Paris is a global fashion hub with a rich history of haute couture and luxury brands, providing students with valuable insights and networking opportunities in the fashion business.",
        "discipline": "Fashion Marketing",
        "cost_of_living": "$75,000 per year",
        "fee": 200
    },
    {
        "name": "New York Art Institute",
        "course_name": "Fine Arts",
        "short_name": "Fine Arts",
        "price": 40000,
        "duration": "3 years",
        "location": "USA",
        "address": "New York, USA",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Graduate",
        "summary": "The New York Art Institute in the USA offers graduate programs in fine arts. Students explore various artistic mediums and techniques while developing their own unique style. The program duration is 3 years. The institute is located in New York, USA. New York City is a global center for the arts with a thriving creative community, providing students with endless inspiration and opportunities to showcase their talent.",
        "discipline": "Fine Arts",
        "cost_of_living": "$80,000 per year",
        "fee": 250
    },
    {
        "name": "Toronto Music Academy",
        "course_name": "Music Production",
        "short_name": "Music",
        "price": 36000,
        "duration": "2 years",
        "location": "Canada",
        "address": "Toronto, Canada",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Toronto Music Academy in Canada offers undergraduate programs in music production. Students learn about recording, mixing, and mastering techniques in state-of-the-art studios. The program duration is 2 years. The academy is located in Toronto, Canada. Toronto has a vibrant music scene and is home to diverse musical styles, providing students with a dynamic and inspiring environment to develop their skills in music production.",
        "discipline": "Music Production",
        "cost_of_living": "$55,000 per year",
        "fee": 220
    },
    {
        "name": "London Drama School",
        "course_name": "Drama Studies",
        "short_name": "Drama",
        "price": 28000,
        "duration": "2 years",
        "location": "UK",
        "address": "London, UK",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Undergraduate",
        "summary": "The London Drama School in the UK offers undergraduate programs in drama studies. Students explore acting, stagecraft, and dramatic theory through practical workshops and performances. The program duration is 2 years. The school is located in London, UK. London has a vibrant theater scene with world-renowned venues and productions, providing students with a rich and immersive experience in drama education.",
        "discipline": "Drama Studies",
        "cost_of_living": "$90,000 per year",
        "fee": 200
    },
    {
        "name": "Rome Art Institute",
        "course_name": "Visual Arts",
        "short_name": "Visual Arts",
        "price": 32000,
        "duration": "2 years",
        "location": "Italy",
        "address": "Rome, Italy",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Graduate",
        "summary": "The Rome Art Institute in Italy offers graduate programs in visual arts. Students explore various artistic mediums and techniques while developing their own unique style. The program duration is 2 years. The institute is located in Rome, Italy. Rome, with its rich history and artistic heritage, provides students with endless inspiration and opportunities to immerse themselves in the vibrant art scene of the eternal city.",
        "discipline": "Visual Arts",
        "cost_of_living": "$70,000 per year",
        "fee": 180
    },
    {
        "name": "Barcelona Culinary Institute",
        "course_name": "Pastry Arts",
        "short_name": "Culinary",
        "price": 30000,
        "duration": "2 years",
        "location": "Spain",
        "address": "Barcelona, Spain",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Undergraduate",
        "summary": "The Barcelona Culinary Institute in Spain offers undergraduate programs in pastry arts. Students learn the art of pastry making from expert chefs and gain hands-on experience in professional kitchens. The program duration is 2 years. The institute is located in Barcelona, Spain. Barcelona is known for its culinary creativity and gastronomic innovation, providing students with a flavorful and immersive learning experience in pastry arts.",
        "discipline": "Pastry Arts",
        "cost_of_living": "$65,000 per year",
        "fee": 200
    },
    {
        "name": "Berlin Drama Academy",
        "course_name": "Acting",
        "short_name": "Acting",
        "price": 35000,
        "duration": "2 years",
        "location": "Germany",
        "address": "Berlin, Germany",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Berlin Drama Academy in Germany offers undergraduate programs in acting. Students receive comprehensive training in acting techniques, voice, and movement. The program duration is 2 years. The academy is located in Berlin, Germany. Berlin, with its vibrant theater scene and avant-garde performances, provides students with a dynamic and inspiring environment to develop their skills and pursue a career in acting.",
        "discipline": "Acting",
        "cost_of_living": "$60,000 per year",
        "fee": 220
    },
    {
        "name": "Sydney Fashion Institute",
        "course_name": "Fashion Merchandising",
        "short_name": "Fashion",
        "price": 32000,
        "duration": "2 years",
        "location": "Australia",
        "address": "Sydney, Australia",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Undergraduate",
        "summary": "The Sydney Fashion Institute in Australia offers undergraduate programs in fashion merchandising. Students learn about retail management, fashion marketing, and trend forecasting. The program duration is 2 years. The institute is located in Sydney, Australia. Sydney, with its dynamic fashion scene and multicultural influences, provides students with a vibrant and diverse learning environment in fashion merchandising.",
        "discipline": "Fashion Merchandising",
        "cost_of_living": "$50,000 per year",
        "fee": 200
    },
    {
        "name": "Vienna Drama School",
        "course_name": "Theater Studies",
        "short_name": "Theater",
        "price": 30000,
        "duration": "2 years",
        "location": "Austria",
        "address": "Vienna, Austria",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Fall"],
        "program_level": "Undergraduate",
        "summary": "The Vienna Drama School in Austria offers undergraduate programs in theater studies. Students explore dramatic theory, playwriting, and performance techniques. The program duration is 2 years. The school is located in Vienna, Austria. Vienna, with its rich theatrical tradition and vibrant arts scene, provides students with an inspiring environment to study theater and pursue their passion for the dramatic arts.",
        "discipline": "Theater Studies",
        "cost_of_living": "$65,000 per year",
        "fee": 200
    },
    {
        "name": "Paris Music Academy",
        "course_name": "Music Education",
        "short_name": "Music",
        "price": 35000,
        "duration": "2 years",
        "location": "France",
        "address": "Paris, France",
        "logo": "https://pbs.twimg.com/profile_images/875797335342817282/JO5OsmxU_400x400.jpg",
        "picture": "https://images.collegedunia.com/public/college_data/images/studyabroad/appImage/college_1090_29-15:00_o-HARVARD-UNIVERSITY-BUILDING-facebook.jpeg",
        "intake": ["Spring"],
        "program_level": "Undergraduate",
        "summary": "The Paris Music Academy in France offers undergraduate programs in music education. Students learn about music theory, pedagogy, and classroom management. The program duration is 2 years. The academy is located in Paris, France. Paris, with its rich musical heritage and cultural diversity, provides students with a vibrant and inspiring environment to study music education and prepare for careers as music educators.",
        "discipline": "Music Education",
        "cost_of_living": "$75,000 per year",
        "fee": 200
    }
]


export const datafilter = [
    "Location",
    "Program Levels",
    "Discipline",
    "Tuition Fee (USD)",
    "Intake"
]

const uniqueLocations = new Set();

Datax.forEach(item => {
    uniqueLocations.add(item.location);
});

export const Location = Array.from(uniqueLocations);
const uniqueProgramLevels = new Set();

Datax.forEach(item => {
    uniqueProgramLevels.add(item.program_level);
});

export const Program = Array.from(uniqueProgramLevels);


const uniqueDisciplines = new Set();
Datax.forEach(item => {
    uniqueDisciplines.add(item.discipline);
});
export const Discpline = Array.from(uniqueDisciplines);

export const Price = [
    "0 - $10,000",
    "$10,000 - $20,000",
    "$20,000 - $40,000",
    "$40,000 - $60,000",
]
export const Intake = [
    "Spring",
    "Fall",
]
export const Duration = [
    "18 months",
    "1 year",
    "2 years",
    "3 years",
    "4 years",
]

export const Sort = [
    "Tuition cost (Low to High)",
    "Tuition cost (High to Low)",
    "Application fee (Low to High)",
    "Application fee (High to Low)",
]

export function addCommas(number: number) {
    return number.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}

// const parsePriceRange = (priceRange: string): [number, number] => {
//     const [minPriceStr, maxPriceStr] = priceRange.split('-');
//     const minPrice = parseInt(minPriceStr.replace(/[^\d.]/g, ''), 10);
//     const maxPrice = maxPriceStr ? parseInt(maxPriceStr.replace(/[^\d.]/g, ''), 10) : Infinity;
//     return [minPrice, maxPrice];
// };

// // Function to filter data based on price range
// const filterDataByPrice = (data: IData[], priceRange: string): IData[] => {
//     const [minPrice, maxPrice] = parsePriceRange(priceRange);
//     return data.filter(item => item.price >= minPrice && item.price <= maxPrice);
// };

// // Function to filter data for multiple price ranges
// export const filterDataForMultiplePriceRanges = (data: IData[], priceRanges: string[]): IData[] => {
//     let filteredData: IData[] = [];
//     priceRanges.forEach(range => {
//         filteredData = filteredData.concat(filterDataByPrice(data, range));
//     });
//     return filteredData;
// };